version: "3.2"
services:
  dev:
    container_name: diffychat
    image: paritytech/ci-linux:production
    working_dir: /var/www/diffychat
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/diffychat/.cargo
    volumes:
      - .:/var/www/diffychat
      #- type: bind
      #source: ./.local
      #target: /root/.local
    command: bash -c "cargo build --release && ./target/release/diffychat --dev --ws-external"
